"""The append-only ledger guard.

The four ledger tables and ``Transfer`` reject ``UPDATE`` and ``DELETE`` at the
database level. The guard lives in a trigger, and ``alembic check`` cannot see
triggers (``env.py`` declares no custom comparators), so the presence test below is
the only thing that stops a future autogenerated migration from dropping it
silently — which is exactly how ``d61ddf38636a`` lost two database invariants.
"""

import uuid

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import text
from sqlalchemy.exc import DatabaseError
from sqlmodel import Session, select

from app.core.config import settings
from app.models import StockMovement
from tests.utils.ledger import load_stock
from tests.utils.utils import random_lower_string

# Asserted verbatim: a rename or a drop must show up as a failure, never as a pass.
GUARD_TRIGGER = "trg_ledger_immutable"

PROTECTED_TABLES = (
    "stockmovement",
    "accountmovement",
    "customeraccountmovement",
    "supplieraccountmovement",
    "transfer",
    "conciliation",
)


def _create_product(client: TestClient, headers: dict[str, str]) -> dict:
    r = client.post(
        f"{settings.API_V1_STR}/uoms/",
        headers=headers,
        json={
            "name": random_lower_string()[:10],
            "abbreviation": random_lower_string()[:3].upper(),
            "decimal_places": 0,
        },
    )
    assert r.status_code == 200, r.text
    r = client.post(
        f"{settings.API_V1_STR}/products/",
        headers=headers,
        json={
            "name": random_lower_string()[:20],
            "uom_id": r.json()["id"],
            "margen_pct": "21.00",
            "costo_actual": "100.00",
            "tax_ids": [],
        },
    )
    assert r.status_code == 200, r.text
    return r.json()


@pytest.fixture
def stock_movement(
    client: TestClient, superuser_token_headers: dict[str, str], db: Session
) -> StockMovement:
    """A real, persisted movement created through the public API."""
    product = _create_product(client, superuser_token_headers)
    load_stock(client, superuser_token_headers, product["id"], "5")
    movement = db.exec(
        select(StockMovement).where(
            StockMovement.product_id == uuid.UUID(product["id"])
        )
    ).first()
    assert movement is not None
    return movement


def test_update_on_a_persisted_movement_is_rejected(
    db: Session, stock_movement: StockMovement
) -> None:
    original = stock_movement.cantidad

    with pytest.raises(DatabaseError):
        db.execute(
            text("UPDATE stockmovement SET cantidad = cantidad + 1 WHERE id = :id"),
            {"id": stock_movement.id},
        )
    db.rollback()

    persisted = db.exec(
        select(StockMovement).where(StockMovement.id == stock_movement.id)
    ).one()
    assert persisted.cantidad == original


def test_delete_on_a_persisted_movement_is_rejected(
    db: Session, stock_movement: StockMovement
) -> None:
    with pytest.raises(DatabaseError):
        db.execute(
            text("DELETE FROM stockmovement WHERE id = :id"), {"id": stock_movement.id}
        )
    db.rollback()

    persisted = db.exec(
        select(StockMovement).where(StockMovement.id == stock_movement.id)
    ).one()
    assert persisted.id == stock_movement.id


def test_a_correction_is_a_new_opposite_sign_movement(
    client: TestClient,
    superuser_token_headers: dict[str, str],
    db: Session,
    stock_movement: StockMovement,
) -> None:
    """The guard blocks mutation without blocking correction."""
    original = stock_movement.cantidad
    load_stock(client, superuser_token_headers, str(stock_movement.product_id), "-5")

    movements = db.exec(
        select(StockMovement).where(
            StockMovement.product_id == stock_movement.product_id
        )
    ).all()
    assert len(movements) == 2
    assert sorted(m.cantidad for m in movements) == [-original, original]

    untouched = next(m for m in movements if m.id == stock_movement.id)
    assert untouched.cantidad == original


def test_a_bulk_update_is_rejected_for_every_row(
    db: Session, stock_movement: StockMovement
) -> None:
    """The guard is per row, so a statement without WHERE cannot slip through."""
    before = {row.id: row.motivo for row in db.exec(select(StockMovement)).all()}
    assert stock_movement.id in before

    with pytest.raises(DatabaseError):
        db.execute(text("UPDATE stockmovement SET motivo = 'mutated'"))
    db.rollback()

    after = {row.id: row.motivo for row in db.exec(select(StockMovement)).all()}
    assert after == before


def test_the_guard_is_present_on_every_protected_table(db: Session) -> None:
    missing: dict[str, set[str]] = {}
    for table in PROTECTED_TABLES:
        names = {
            row[0]
            for row in db.execute(
                text(
                    "SELECT tgname FROM pg_trigger "
                    "WHERE tgrelid = to_regclass(:table) AND NOT tgisinternal"
                ),
                {"table": table},
            ).all()
        }
        if GUARD_TRIGGER not in names:
            missing[table] = names

    assert not missing, f"tables without the append-only guard: {missing}"
