#!/usr/bin/env bash
# Fail when SQLModel metadata and the migrated database disagree.
#
# This is the gate that would have caught migration ``d61ddf38636a``: it dropped
# ``uq_cashregistersession_single_open`` and ``ck_product_stock_maximo_gte_minimo``
# by carrying two autogenerated operations nobody hand-removed, and because both
# objects existed only in migrations (never in metadata) autogenerate could not see
# them — so the loss stayed invisible for eleven revisions.
#
# Requires a reachable database that has been migrated to head. In CI this runs
# right after ``scripts/prestart.sh``, i.e. against a schema built from scratch by
# ``alembic upgrade head``, which is precisely the comparison that matters.

set -e
set -x

alembic check
