// This file is auto-generated by @hey-api/openapi-ts

export type AccountMovementPublic = {
    id: string;
    financial_account_id: string;
    document_id?: (string | null);
    payment_method_id?: (string | null);
    transfer_id?: (string | null);
    monto: string;
    tipo: AccountMovementType;
    fecha: string;
    fecha_acreditacion?: (string | null);
    conciliado: boolean;
    user_id: string;
    created_at?: (string | null);
    account_name?: (string | null);
    document_numero?: (string | null);
};

export type AccountMovementType = 'pago' | 'cobro' | 'comision' | 'transferencia' | 'ajuste';

export type AttributeCreate = {
    name: string;
    values?: Array<(string)>;
};

export type AttributePublic = {
    id: string;
    name: string;
    values?: Array<AttributeValuePublic>;
};

export type AttributeUpdate = {
    name?: (string | null);
    values?: (Array<(string)> | null);
};

export type AttributeValuePublic = {
    id: string;
    attribute_id: string;
    value: string;
};

export type BackupFrequency = 'daily' | 'weekly' | 'monthly';

export type BackupKind = 'manual' | 'scheduled';

export type BackupPublic = {
    id: string;
    filename: string;
    size_bytes: number;
    kind: BackupKind;
    status: BackupStatus;
    error?: (string | null);
    created_by_id?: (string | null);
    created_at?: (string | null);
    created_by_name?: (string | null);
};

export type BackupSchedulePublic = {
    enabled: boolean;
    frequency: BackupFrequency;
    run_time: string;
    day_of_week?: (number | null);
    day_of_month?: (number | null);
    retention: number;
    next_run_at?: (string | null);
    last_run_at?: (string | null);
    last_status?: (BackupStatus | null);
    last_error?: (string | null);
};

export type BackupScheduleUpdate = {
    enabled?: (boolean | null);
    frequency?: (BackupFrequency | null);
    run_time?: (string | null);
    day_of_week?: (number | null);
    day_of_month?: (number | null);
    retention?: (number | null);
};

export type BackupStatus = 'success' | 'failed';

export type Barcode = {
    id?: string;
    code: string;
    product_id: string;
    variant_id?: (string | null);
};

export type BarcodeCreate = {
    code: string;
    product_id: string;
    variant_id?: (string | null);
};

export type BarcodePublic = {
    id: string;
    code: string;
    product_id: string;
    variant_id?: (string | null);
};

export type Body_backups_restore_backup = {
    file?: (string | null);
    backup_id?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BusinessSettingsPublic = {
    id: number;
    business_name: string;
    address?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    cuit?: (string | null);
    condicion_fiscal: TaxCondition;
    allow_negative_stock: boolean;
    enable_variants: boolean;
    default_iva?: (string | null);
};

export type BusinessSettingsUpdate = {
    business_name?: (string | null);
    address?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    cuit?: (string | null);
    condicion_fiscal?: (TaxCondition | null);
    allow_negative_stock?: (boolean | null);
    enable_variants?: (boolean | null);
    default_iva?: (number | string | null);
};

export type CategoryCreate = {
    name: string;
    parent_id?: (string | null);
};

export type CategoryPublic = {
    name: string;
    id: string;
    parent_id?: (string | null);
};

export type CategoryUpdate = {
    name?: (string | null);
    parent_id?: (string | null);
};

/**
 * Cost update proposal surfaced by a purchase, decided by the user.
 */
export type CostChangeSuggestion = {
    supplier_id: string;
    product_id: string;
    product_name: string;
    previous_cost?: (string | null);
    suggested_cost: string;
    is_reference: boolean;
};

export type CounterpartType = 'customer' | 'supplier';

export type CustomerAccountMovementPublic = {
    id: string;
    customer_id: string;
    document_id?: (string | null);
    monto: string;
    created_at?: (string | null);
    document_numero?: (string | null);
};

export type CustomerCreate = {
    razon_social: string;
    documento?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    address?: (string | null);
    condicion_fiscal?: TaxCondition;
    limite_credito?: (number | string);
    is_active?: boolean;
};

export type CustomerPublic = {
    razon_social: string;
    documento?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    address?: (string | null);
    condicion_fiscal?: TaxCondition;
    limite_credito?: string;
    is_active?: boolean;
    id: string;
    saldo: string;
    created_at?: (string | null);
};

export type CustomerUpdate = {
    razon_social?: (string | null);
    documento?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    address?: (string | null);
    condicion_fiscal?: (TaxCondition | null);
    limite_credito?: (number | string | null);
    is_active?: (boolean | null);
};

/**
 * A receipt imputed to a document, resolved for display.
 */
export type DocumentAllocationPublic = {
    receipt_document_id: string;
    receipt_numero: string;
    fecha?: (string | null);
    monto: string;
};

export type DocumentCreate = {
    document_type_id: string;
    contraparte_id?: (string | null);
    fecha?: (string | null);
    descuento_total?: (number | string);
    lines: Array<DocumentLineCreate>;
    payments?: Array<DocumentPaymentCreate>;
};

export type DocumentLineCreate = {
    product_id: string;
    variant_id?: (string | null);
    cantidad: (number | string);
    precio_unit?: (number | string | null);
    descuento_pct?: (number | string);
    descuento_monto?: (number | string | null);
    tax_ids?: (Array<(string)> | null);
    costo_unitario?: (number | string | null);
};

export type DocumentLinePublic = {
    id: string;
    orden: number;
    product_id: string;
    variant_id?: (string | null);
    cantidad: string;
    precio_unit: string;
    costo_unitario: string;
    descuento_pct: string;
    descuento_monto: string;
    subtotal_line: string;
    taxes?: Array<DocumentLineTaxPublic>;
    cantidad_pendiente?: (string | null);
};

export type DocumentLineTaxPublic = {
    id: string;
    tax_id: string;
    base: string;
    monto: string;
    aplicado: boolean;
};

export type DocumentOperation = 'venta' | 'compra' | 'cotizacion' | 'ajuste' | 'recibo';

export type DocumentPaymentCreate = {
    payment_method_id: string;
    monto: (number | string);
    comision_pct?: (number | string | null);
    fecha_acreditacion?: (string | null);
};

export type DocumentPaymentPublic = {
    id: string;
    payment_method_id: string;
    monto: string;
    comision_pct?: (string | null);
    fecha_acreditacion?: (string | null);
    conciliado: boolean;
};

export type DocumentPublic = {
    id: string;
    document_type_id: string;
    numero: string;
    year: number;
    fecha: string;
    contraparte_type?: (CounterpartType | null);
    contraparte_id?: (string | null);
    user_id: string;
    estado: DocumentStatus;
    subtotal: string;
    descuento_total: string;
    total: string;
    favor_monto?: string;
    parent_document_id?: (string | null);
    created_at?: (string | null);
    document_type: DocumentTypePublic;
    lines?: Array<DocumentLinePublic>;
    taxes?: Array<DocumentTaxPublic>;
    payments?: Array<DocumentPaymentPublic>;
    contraparte_name?: (string | null);
    child_document_id?: (string | null);
    child_document_numero?: (string | null);
    cost_change_suggestions?: Array<CostChangeSuggestion>;
};

export type DocumentStatus = 'active' | 'voided';

export type DocumentTaxPublic = {
    id: string;
    tax_id: string;
    base: string;
    monto: string;
};

export type DocumentTypePublic = {
    id: string;
    name: string;
    prefix: string;
    operation: DocumentOperation;
    signo_stock: number;
    signo_caja: number;
    es_fiscal: boolean;
    tipo_contraparte?: (CounterpartType | null);
    void_document_type_id?: (string | null);
    is_active: boolean;
};

/**
 * Editable fields of a document type; signs and operation stay fixed.
 */
export type DocumentTypeUpdate = {
    name?: (string | null);
    prefix?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Empty ``lines`` voids everything still pending (total void).
 */
export type DocumentVoidCreate = {
    lines?: Array<DocumentVoidLine>;
    payments?: Array<DocumentPaymentCreate>;
};

export type DocumentVoidLine = {
    document_line_id: string;
    cantidad: (number | string);
};

export type FinancialAccountCreate = {
    name: string;
    currency?: string;
};

export type FinancialAccountPublic = {
    id: string;
    name: string;
    saldo: string;
    currency: string;
};

export type FinancialAccountUpdate = {
    name?: (string | null);
    currency?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LowStockRow = {
    id: string;
    name: string;
    sku?: (string | null);
    category_name?: (string | null);
    stock_current: string;
    stock_minimo?: (string | null);
    stock_maximo?: (string | null);
};

export type MarginRow = {
    product_id: string;
    name: string;
    units: string;
    revenue: string;
    cost: string;
    margin: string;
    margin_pct?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * A document of a counterpart with a still-unpaid portion.
 */
export type OutstandingDocumentPublic = {
    document_id: string;
    numero: string;
    fecha: string;
    total: string;
    pendiente: string;
};

export type Page_AccountMovementPublic_ = {
    data: Array<AccountMovementPublic>;
    count: number;
};

export type Page_AttributePublic_ = {
    data: Array<AttributePublic>;
    count: number;
};

export type Page_BackupPublic_ = {
    data: Array<BackupPublic>;
    count: number;
};

export type Page_CategoryPublic_ = {
    data: Array<CategoryPublic>;
    count: number;
};

export type Page_CustomerAccountMovementPublic_ = {
    data: Array<CustomerAccountMovementPublic>;
    count: number;
};

export type Page_CustomerPublic_ = {
    data: Array<CustomerPublic>;
    count: number;
};

export type Page_DocumentPublic_ = {
    data: Array<DocumentPublic>;
    count: number;
};

export type Page_DocumentTypePublic_ = {
    data: Array<DocumentTypePublic>;
    count: number;
};

export type Page_FinancialAccountPublic_ = {
    data: Array<FinancialAccountPublic>;
    count: number;
};

export type Page_ItemPublic_ = {
    data: Array<ItemPublic>;
    count: number;
};

export type Page_OutstandingDocumentPublic_ = {
    data: Array<OutstandingDocumentPublic>;
    count: number;
};

export type Page_PaymentMethodPublic_ = {
    data: Array<PaymentMethodPublic>;
    count: number;
};

export type Page_PermissionPublic_ = {
    data: Array<PermissionPublic>;
    count: number;
};

export type Page_ProductPublic_ = {
    data: Array<ProductPublic>;
    count: number;
};

export type Page_RolePublic_ = {
    data: Array<RolePublic>;
    count: number;
};

export type Page_StockMovementPublic_ = {
    data: Array<StockMovementPublic>;
    count: number;
};

export type Page_SupplierAccountMovementPublic_ = {
    data: Array<SupplierAccountMovementPublic>;
    count: number;
};

export type Page_SupplierProductPublic_ = {
    data: Array<SupplierProductPublic>;
    count: number;
};

export type Page_SupplierPublic_ = {
    data: Array<SupplierPublic>;
    count: number;
};

export type Page_TaxPublic_ = {
    data: Array<TaxPublic>;
    count: number;
};

export type Page_TransferPublic_ = {
    data: Array<TransferPublic>;
    count: number;
};

export type Page_UoMPublic_ = {
    data: Array<UoMPublic>;
    count: number;
};

export type Page_UserPublic_ = {
    data: Array<UserPublic>;
    count: number;
};

export type PaymentMethodCreate = {
    name: string;
    financial_account_id: string;
    marks_paid?: boolean;
    requiere_conciliacion?: boolean;
};

export type PaymentMethodPublic = {
    id: string;
    name: string;
    financial_account_id: string;
    marks_paid: boolean;
    requiere_conciliacion: boolean;
};

export type PaymentMethodUpdate = {
    name?: (string | null);
    financial_account_id?: (string | null);
    marks_paid?: (boolean | null);
    requiere_conciliacion?: (boolean | null);
};

/**
 * Input for a standalone payment against a counterpart's current account.
 */
export type PaymentReceiptCreate = {
    contraparte_type: CounterpartType;
    contraparte_id: string;
    fecha?: (string | null);
    payments: Array<DocumentPaymentCreate>;
};

export type PaymentReceiptPublic = {
    document: DocumentPublic;
    allocations?: Array<ReceiptAllocationPublic>;
};

export type PermissionPublic = {
    id: string;
    code: string;
    description?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductCreate = {
    name: string;
    sku?: (string | null);
    category_id?: (string | null);
    uom_id: string;
    description?: (string | null);
    is_active?: boolean;
    margen_pct?: (number | string);
    costo_actual?: (number | string);
    stock_minimo?: (number | string | null);
    stock_maximo?: (number | string | null);
    tax_ids?: Array<(string)>;
};

export type ProductPublic = {
    id: string;
    name: string;
    sku?: (string | null);
    category_id?: (string | null);
    uom_id: string;
    description?: (string | null);
    is_active: boolean;
    margen_pct: string;
    costo_actual: string;
    precio_venta: string;
    stock_current: string;
    stock_minimo?: (string | null);
    stock_maximo?: (string | null);
    created_at?: (string | null);
    taxes?: Array<TaxPublic>;
    variants?: Array<ProductVariantPublic>;
    barcodes?: Array<BarcodePublic>;
};

export type ProductUpdate = {
    name?: (string | null);
    sku?: (string | null);
    category_id?: (string | null);
    uom_id?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
    margen_pct?: (number | string | null);
    costo_actual?: (number | string | null);
    stock_minimo?: (number | string | null);
    stock_maximo?: (number | string | null);
    tax_ids?: (Array<(string)> | null);
};

export type ProductVariantCreate = {
    product_id: string;
    sku_suffix?: (string | null);
    attribute_value_ids?: Array<(string)>;
};

export type ProductVariantPublic = {
    id: string;
    product_id: string;
    sku_suffix?: (string | null);
    stock_current: string;
    barcodes?: Array<BarcodePublic>;
    attribute_values?: Array<AttributeValuePublic>;
};

/**
 * A document settled by a receipt, resolved for display.
 */
export type ReceiptAllocationPublic = {
    document_id: string;
    numero: string;
    fecha?: (string | null);
    monto: string;
};

export type ReorderRow = {
    id: string;
    name: string;
    sku?: (string | null);
    category_id?: (string | null);
    category_name?: (string | null);
    stock_current: string;
    stock_minimo?: (string | null);
    stock_maximo?: (string | null);
    missing?: (string | null);
    reference_cost?: (string | null);
    estimated_cost?: (string | null);
};

export type RestoreState = 'idle' | 'running' | 'success' | 'failed';

/**
 * Restore progress, sourced from the restore state file (not the DB:
 * the DB itself is dropped while a restore runs).
 */
export type RestoreStatusPublic = {
    estado: RestoreState;
    source_filename?: (string | null);
    started_at?: (string | null);
    finished_at?: (string | null);
    error?: (string | null);
};

export type RoleCreate = {
    name: string;
    description?: (string | null);
    permission_ids?: Array<(string)>;
};

export type RolePublic = {
    name: string;
    description?: (string | null);
    id: string;
    permissions?: Array<PermissionPublic>;
};

export type RoleUpdate = {
    name?: (string | null);
    description?: (string | null);
    permission_ids?: (Array<(string)> | null);
};

export type SalesPerDayRow = {
    fecha: string;
    count: number;
    subtotal: string;
    descuento_total: string;
    total: string;
};

export type StockMovementPublic = {
    id: string;
    product_id: string;
    variant_id?: (string | null);
    document_id: string;
    document_line_id?: (string | null);
    signo: number;
    cantidad: string;
    motivo: string;
    user_id: string;
    created_at?: (string | null);
    product_name?: (string | null);
    document_numero?: (string | null);
};

export type SupplierAccountMovementPublic = {
    id: string;
    supplier_id: string;
    document_id?: (string | null);
    monto: string;
    created_at?: (string | null);
    document_numero?: (string | null);
};

export type SupplierCreate = {
    razon_social: string;
    documento?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    address?: (string | null);
    condicion_fiscal?: TaxCondition;
    is_active?: boolean;
};

export type SupplierProductCreate = {
    supplier_id: string;
    product_id: string;
    costo_actual: (number | string);
    es_referencia?: boolean;
    es_default?: boolean;
};

export type SupplierProductPublic = {
    supplier_id: string;
    product_id: string;
    costo_anterior: string;
    costo_actual: string;
    fecha_actualizacion?: (string | null);
    es_referencia: boolean;
    es_default: boolean;
    created_at?: (string | null);
    supplier_name?: (string | null);
    product_name?: (string | null);
};

export type SupplierProductUpdate = {
    costo_actual?: (number | string | null);
    es_referencia?: (boolean | null);
    es_default?: (boolean | null);
};

export type SupplierPublic = {
    razon_social: string;
    documento?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    address?: (string | null);
    condicion_fiscal?: TaxCondition;
    is_active?: boolean;
    id: string;
    saldo: string;
    created_at?: (string | null);
};

export type SupplierUpdate = {
    razon_social?: (string | null);
    documento?: (string | null);
    phone?: (string | null);
    email?: (string | null);
    address?: (string | null);
    condicion_fiscal?: (TaxCondition | null);
    is_active?: (boolean | null);
};

export type TaxAppliesTo = 'linea' | 'documento';

export type TaxCondition = 'RI' | 'Monotributo' | 'Exento' | 'Consumidor Final';

export type TaxCreate = {
    name: string;
    code: string;
    tipo: TaxType;
    rate: (number | string);
    is_percent?: boolean;
    aplica_a?: TaxAppliesTo;
    is_default?: boolean;
    is_active?: boolean;
};

export type TaxPublic = {
    name: string;
    code: string;
    tipo: TaxType;
    rate: string;
    is_percent?: boolean;
    aplica_a?: TaxAppliesTo;
    is_default?: boolean;
    is_active?: boolean;
    id: string;
};

export type TaxType = 'IVA' | 'IIBB' | 'PercGan' | 'Interno' | 'Otro';

export type TaxUpdate = {
    name?: (string | null);
    code?: (string | null);
    tipo?: (TaxType | null);
    rate?: (number | string | null);
    is_percent?: (boolean | null);
    aplica_a?: (TaxAppliesTo | null);
    is_default?: (boolean | null);
    is_active?: (boolean | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TransferCreate = {
    from_account_id: string;
    to_account_id: string;
    monto: (number | string);
    fecha?: (string | null);
    descripcion?: (string | null);
};

export type TransferPublic = {
    id: string;
    from_account_id: string;
    to_account_id: string;
    monto: string;
    fecha: string;
    descripcion?: (string | null);
    user_id: string;
    created_at?: (string | null);
};

export type UoMCreate = {
    name: string;
    abbreviation: string;
    decimal_places?: number;
};

export type UoMPublic = {
    name: string;
    abbreviation: string;
    decimal_places?: number;
    id: string;
};

export type UoMUpdate = {
    name?: (string | null);
    abbreviation?: (string | null);
    decimal_places?: (number | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
    role_ids?: Array<(string)>;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    roles?: Array<RolePublic>;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
    role_ids?: (Array<(string)> | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VatRow = {
    tax_code: string;
    tax_name: string;
    tipo: TaxType;
    rate: string;
    is_percent: boolean;
    applies_to: TaxAppliesTo;
    base: string;
    monto: string;
    count: number;
};

export type AccountMovementsReadAccountMovementsData = {
    conciliado?: (boolean | null);
    fechaDesde?: (string | null);
    fechaHasta?: (string | null);
    financialAccountId?: (string | null);
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type AccountMovementsReadAccountMovementsResponse = (Page_AccountMovementPublic_);

export type AccountMovementsConciliateMovementData = {
    movementId: string;
};

export type AccountMovementsConciliateMovementResponse = (AccountMovementPublic);

export type AttributesReadAttributesData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type AttributesReadAttributesResponse = (Page_AttributePublic_);

export type AttributesCreateAttributeData = {
    requestBody: AttributeCreate;
};

export type AttributesCreateAttributeResponse = (AttributePublic);

export type AttributesUpdateAttributeData = {
    attributeId: string;
    requestBody: AttributeUpdate;
};

export type AttributesUpdateAttributeResponse = (AttributePublic);

export type AttributesDeleteAttributeData = {
    attributeId: string;
};

export type AttributesDeleteAttributeResponse = (Message);

export type BackupsReadBackupsData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type BackupsReadBackupsResponse = (Page_BackupPublic_);

export type BackupsCreateBackupNowResponse = (BackupPublic);

export type BackupsDownloadBackupData = {
    backupId: string;
};

export type BackupsDownloadBackupResponse = (unknown);

export type BackupsDeleteBackupData = {
    backupId: string;
};

export type BackupsDeleteBackupResponse = (void);

export type BackupsReadBackupScheduleResponse = (BackupSchedulePublic);

export type BackupsUpdateBackupScheduleData = {
    requestBody: BackupScheduleUpdate;
};

export type BackupsUpdateBackupScheduleResponse = (BackupSchedulePublic);

export type BackupsReadRestoreStatusResponse = (RestoreStatusPublic);

export type BackupsRestoreBackupData = {
    formData?: Body_backups_restore_backup;
};

export type BackupsRestoreBackupResponse = (RestoreStatusPublic);

export type BusinessSettingsReadBusinessSettingsResponse = (BusinessSettingsPublic);

export type BusinessSettingsUpdateBusinessSettingsData = {
    requestBody: BusinessSettingsUpdate;
};

export type BusinessSettingsUpdateBusinessSettingsResponse = (BusinessSettingsPublic);

export type CategoriesReadCategoriesData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type CategoriesReadCategoriesResponse = (Page_CategoryPublic_);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesReadCategoryData = {
    categoryId: string;
};

export type CategoriesReadCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryData = {
    categoryId: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesDeleteCategoryData = {
    categoryId: string;
};

export type CategoriesDeleteCategoryResponse = (Message);

export type CustomersReadCustomersData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type CustomersReadCustomersResponse = (Page_CustomerPublic_);

export type CustomersCreateCustomerData = {
    requestBody: CustomerCreate;
};

export type CustomersCreateCustomerResponse = (CustomerPublic);

export type CustomersReadCustomerData = {
    customerId: string;
};

export type CustomersReadCustomerResponse = (CustomerPublic);

export type CustomersUpdateCustomerData = {
    customerId: string;
    requestBody: CustomerUpdate;
};

export type CustomersUpdateCustomerResponse = (CustomerPublic);

export type CustomersDeleteCustomerData = {
    customerId: string;
};

export type CustomersDeleteCustomerResponse = (Message);

export type CustomersReadCustomerAccountMovementsData = {
    customerId: string;
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type CustomersReadCustomerAccountMovementsResponse = (Page_CustomerAccountMovementPublic_);

export type DocumentsSuggestFiscalSaleTypeData = {
    customerId: string;
};

export type DocumentsSuggestFiscalSaleTypeResponse = (DocumentTypePublic);

export type DocumentsReadDocumentCreatorsResponse = (Array<UserPublic>);

export type DocumentsReadDocumentsData = {
    documentTypeId?: (string | null);
    fechaDesde?: (string | null);
    fechaHasta?: (string | null);
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
    userId?: (string | null);
};

export type DocumentsReadDocumentsResponse = (Page_DocumentPublic_);

export type DocumentsCreateDocumentData = {
    requestBody: DocumentCreate;
};

export type DocumentsCreateDocumentResponse = (DocumentPublic);

export type DocumentsReadDocumentData = {
    documentId: string;
};

export type DocumentsReadDocumentResponse = (DocumentPublic);

export type DocumentsReadDocumentAllocationsData = {
    documentId: string;
};

export type DocumentsReadDocumentAllocationsResponse = (Array<DocumentAllocationPublic>);

export type DocumentsVoidDocumentData = {
    documentId: string;
    requestBody: DocumentVoidCreate;
};

export type DocumentsVoidDocumentResponse = (DocumentPublic);

export type DocumentsConvertToInvoiceData = {
    documentId: string;
};

export type DocumentsConvertToInvoiceResponse = (DocumentPublic);

export type DocumentTypesReadDocumentTypesData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type DocumentTypesReadDocumentTypesResponse = (Page_DocumentTypePublic_);

export type DocumentTypesUpdateDocumentTypeData = {
    documentTypeId: string;
    requestBody: DocumentTypeUpdate;
};

export type DocumentTypesUpdateDocumentTypeResponse = (DocumentTypePublic);

export type FinancialAccountsReadFinancialAccountsData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type FinancialAccountsReadFinancialAccountsResponse = (Page_FinancialAccountPublic_);

export type FinancialAccountsCreateFinancialAccountData = {
    requestBody: FinancialAccountCreate;
};

export type FinancialAccountsCreateFinancialAccountResponse = (FinancialAccountPublic);

export type FinancialAccountsReadFinancialAccountData = {
    accountId: string;
};

export type FinancialAccountsReadFinancialAccountResponse = (FinancialAccountPublic);

export type FinancialAccountsUpdateFinancialAccountData = {
    accountId: string;
    requestBody: FinancialAccountUpdate;
};

export type FinancialAccountsUpdateFinancialAccountResponse = (FinancialAccountPublic);

export type FinancialAccountsDeleteFinancialAccountData = {
    accountId: string;
};

export type FinancialAccountsDeleteFinancialAccountResponse = (Message);

export type ItemsReadItemsData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type ItemsReadItemsResponse = (Page_ItemPublic_);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PaymentMethodsReadPaymentMethodsData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type PaymentMethodsReadPaymentMethodsResponse = (Page_PaymentMethodPublic_);

export type PaymentMethodsCreatePaymentMethodData = {
    requestBody: PaymentMethodCreate;
};

export type PaymentMethodsCreatePaymentMethodResponse = (PaymentMethodPublic);

export type PaymentMethodsReadPaymentMethodData = {
    paymentMethodId: string;
};

export type PaymentMethodsReadPaymentMethodResponse = (PaymentMethodPublic);

export type PaymentMethodsUpdatePaymentMethodData = {
    paymentMethodId: string;
    requestBody: PaymentMethodUpdate;
};

export type PaymentMethodsUpdatePaymentMethodResponse = (PaymentMethodPublic);

export type PaymentMethodsDeletePaymentMethodData = {
    paymentMethodId: string;
};

export type PaymentMethodsDeletePaymentMethodResponse = (Message);

export type PaymentsReadOutstandingData = {
    contraparteId: string;
    contraparteType: CounterpartType;
};

export type PaymentsReadOutstandingResponse = (Page_OutstandingDocumentPublic_);

export type PaymentsCreatePaymentReceiptData = {
    requestBody: PaymentReceiptCreate;
};

export type PaymentsCreatePaymentReceiptResponse = (PaymentReceiptPublic);

export type PaymentsReadReceiptAllocationsData = {
    receiptDocumentId: string;
};

export type PaymentsReadReceiptAllocationsResponse = (Array<ReceiptAllocationPublic>);

export type PermissionsReadPermissionsData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type PermissionsReadPermissionsResponse = (Page_PermissionPublic_);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsReadProductsData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type ProductsReadProductsResponse = (Page_ProductPublic_);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsSearchProductsData = {
    limit?: number;
    q: string;
};

export type ProductsSearchProductsResponse = (Page_ProductPublic_);

export type ProductsReadProductData = {
    productId: string;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    productId: string;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    productId: string;
};

export type ProductsDeleteProductResponse = (Message);

export type ProductsAddBarcodeData = {
    productId: string;
    requestBody: BarcodeCreate;
};

export type ProductsAddBarcodeResponse = (Barcode);

export type ProductsDeleteBarcodeData = {
    barcodeId: string;
};

export type ProductsDeleteBarcodeResponse = (Message);

export type ProductsCreateVariantData = {
    productId: string;
    requestBody: ProductVariantCreate;
};

export type ProductsCreateVariantResponse = (ProductVariantPublic);

export type ProductsDeleteVariantData = {
    variantId: string;
};

export type ProductsDeleteVariantResponse = (Message);

export type ReportsSalesPerDayData = {
    desde?: (string | null);
    hasta?: (string | null);
};

export type ReportsSalesPerDayResponse = (Array<SalesPerDayRow>);

export type ReportsLowStockResponse = (Array<LowStockRow>);

export type ReportsMarginReportData = {
    desde?: (string | null);
    hasta?: (string | null);
};

export type ReportsMarginReportResponse = (Array<MarginRow>);

export type ReportsVatReportData = {
    desde?: (string | null);
    hasta?: (string | null);
};

export type ReportsVatReportResponse = (Array<VatRow>);

export type ReportsReorderReportData = {
    categoryId?: (string | null);
    supplierId?: (string | null);
};

export type ReportsReorderReportResponse = (Array<ReorderRow>);

export type RolesReadRolesData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type RolesReadRolesResponse = (Page_RolePublic_);

export type RolesCreateRoleData = {
    requestBody: RoleCreate;
};

export type RolesCreateRoleResponse = (RolePublic);

export type RolesReadRoleData = {
    roleId: string;
};

export type RolesReadRoleResponse = (RolePublic);

export type RolesUpdateRoleData = {
    requestBody: RoleUpdate;
    roleId: string;
};

export type RolesUpdateRoleResponse = (RolePublic);

export type RolesDeleteRoleData = {
    roleId: string;
};

export type RolesDeleteRoleResponse = (Message);

export type StockMovementsReadStockMovementsData = {
    documentId?: (string | null);
    fechaDesde?: (string | null);
    fechaHasta?: (string | null);
    /**
     * Items per page
     */
    limit?: number;
    productId?: (string | null);
    /**
     * Items to skip
     */
    skip?: number;
};

export type StockMovementsReadStockMovementsResponse = (Page_StockMovementPublic_);

export type SupplierProductsReadSupplierProductsData = {
    /**
     * Items per page
     */
    limit?: number;
    productId?: (string | null);
    /**
     * Items to skip
     */
    skip?: number;
    supplierId?: (string | null);
};

export type SupplierProductsReadSupplierProductsResponse = (Page_SupplierProductPublic_);

export type SupplierProductsCreateSupplierProductData = {
    requestBody: SupplierProductCreate;
};

export type SupplierProductsCreateSupplierProductResponse = (SupplierProductPublic);

export type SupplierProductsUpdateSupplierProductData = {
    productId: string;
    requestBody: SupplierProductUpdate;
    supplierId: string;
};

export type SupplierProductsUpdateSupplierProductResponse = (SupplierProductPublic);

export type SupplierProductsDeleteSupplierProductData = {
    productId: string;
    supplierId: string;
};

export type SupplierProductsDeleteSupplierProductResponse = (Message);

export type SuppliersReadSuppliersData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type SuppliersReadSuppliersResponse = (Page_SupplierPublic_);

export type SuppliersCreateSupplierData = {
    requestBody: SupplierCreate;
};

export type SuppliersCreateSupplierResponse = (SupplierPublic);

export type SuppliersReadSupplierData = {
    supplierId: string;
};

export type SuppliersReadSupplierResponse = (SupplierPublic);

export type SuppliersUpdateSupplierData = {
    requestBody: SupplierUpdate;
    supplierId: string;
};

export type SuppliersUpdateSupplierResponse = (SupplierPublic);

export type SuppliersDeleteSupplierData = {
    supplierId: string;
};

export type SuppliersDeleteSupplierResponse = (Message);

export type SuppliersReadSupplierAccountMovementsData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
    supplierId: string;
};

export type SuppliersReadSupplierAccountMovementsResponse = (Page_SupplierAccountMovementPublic_);

export type TaxesReadTaxesData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type TaxesReadTaxesResponse = (Page_TaxPublic_);

export type TaxesCreateTaxData = {
    requestBody: TaxCreate;
};

export type TaxesCreateTaxResponse = (TaxPublic);

export type TaxesUpdateTaxData = {
    requestBody: TaxUpdate;
    taxId: string;
};

export type TaxesUpdateTaxResponse = (TaxPublic);

export type TaxesDeleteTaxData = {
    taxId: string;
};

export type TaxesDeleteTaxResponse = (Message);

export type TransfersReadTransfersData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type TransfersReadTransfersResponse = (Page_TransferPublic_);

export type TransfersCreateTransferData = {
    requestBody: TransferCreate;
};

export type TransfersCreateTransferResponse = (TransferPublic);

export type UomsReadUomsData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type UomsReadUomsResponse = (Page_UoMPublic_);

export type UomsCreateUomData = {
    requestBody: UoMCreate;
};

export type UomsCreateUomResponse = (UoMPublic);

export type UomsUpdateUomData = {
    requestBody: UoMUpdate;
    uomId: string;
};

export type UomsUpdateUomResponse = (UoMPublic);

export type UomsDeleteUomData = {
    uomId: string;
};

export type UomsDeleteUomResponse = (Message);

export type UsersReadUsersData = {
    /**
     * Items per page
     */
    limit?: number;
    /**
     * Items to skip
     */
    skip?: number;
};

export type UsersReadUsersResponse = (Page_UserPublic_);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);