"""Add the append-only guard for the ledger tables

Rejects ``UPDATE`` and ``DELETE`` on ``stockmovement``, ``accountmovement``,
``customeraccountmovement``, ``supplieraccountmovement`` and ``transfer``, so the
append-only invariant is enforced by the database instead of by convention. A
correction is a new opposite-sign movement referencing the original row; stored
rows are never rewritten.

The guard is a trigger and Alembic autogenerate does not reflect triggers, so
``alembic check`` cannot see it. ``tests/api/routes/test_ledger_immutability.py``
asserts its presence on every protected table for that reason: without that test,
one autogenerated migration could drop the guard and nothing would notice.

Revision ID: 1809708fd773
Revises: 39c9148ae5e4
Create Date: 2026-09-10 19:22:11.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1809708fd773"
down_revision = "39c9148ae5e4"
branch_labels = None
depends_on = None

GUARD_FUNCTION = "tempos_reject_ledger_mutation"
GUARD_TRIGGER = "trg_ledger_immutable"
PROTECTED_TABLES = (
    "stockmovement",
    "accountmovement",
    "customeraccountmovement",
    "supplieraccountmovement",
    "transfer",
)


def upgrade() -> None:
    op.execute(
        f"""
        CREATE OR REPLACE FUNCTION {GUARD_FUNCTION}() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'ledger tables are append-only: % is rejected on %',
                TG_OP, TG_TABLE_NAME
                USING ERRCODE = 'restrict_violation',
                      HINT = 'insert an opposite-sign movement referencing the row';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in PROTECTED_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {GUARD_TRIGGER} ON {table}")
        op.execute(
            f"CREATE TRIGGER {GUARD_TRIGGER} BEFORE UPDATE OR DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION {GUARD_FUNCTION}()"
        )


def downgrade() -> None:
    for table in PROTECTED_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {GUARD_TRIGGER} ON {table}")
    op.execute(f"DROP FUNCTION IF EXISTS {GUARD_FUNCTION}()")
