"""Add is_default to Tax

Revision ID: 27c625ca40f7
Revises: 2903c6885f02
Create Date: 2026-07-28 17:01:06.053476

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '27c625ca40f7'
down_revision = '2903c6885f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tax',
        sa.Column('is_default', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.alter_column('tax', 'is_default', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax', 'is_default')
    # ### end Alembic commands ###
