"""Add catalog models

Revision ID: 2903c6885f02
Revises: e34bdf56fb4d
Create Date: 2026-07-23 07:57:36.030150

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2903c6885f02'
down_revision = 'e34bdf56fb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('IVA', 'IIBB', 'PERC_GAN', 'INTERNO', 'OTRO', name='taxtype'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_percent', sa.Boolean(), nullable=False),
    sa.Column('aplica_a', sa.Enum('LINEA', 'DOCUMENTO', name='taxappliesto'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_code'), 'tax', ['code'], unique=True)
    op.create_table('uom',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('abbreviation', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attributevalue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attribute_id', sa.Uuid(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('uom_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('margen_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('costo_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('stock_maximo', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_current', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['uom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producttax',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('tax_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_id'], ['tax.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'tax_id')
    )
    op.create_table('productvariant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku_suffix', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('stock_current', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barcode',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['productvariant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcode_code'), 'barcode', ['code'], unique=True)
    op.create_table('productvariantattribute',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('attribute_value_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attributevalue.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['productvariant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'attribute_value_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productvariantattribute')
    op.drop_index(op.f('ix_barcode_code'), table_name='barcode')
    op.drop_table('barcode')
    op.drop_table('productvariant')
    op.drop_table('producttax')
    op.drop_table('product')
    op.drop_table('attributevalue')
    op.drop_table('uom')
    op.drop_index(op.f('ix_tax_code'), table_name='tax')
    op.drop_table('tax')
    op.drop_table('category')
    op.drop_table('attribute')
    # ### end Alembic commands ###
