"""Restore the dropped cash-session guard and product check constraint

``d61ddf38636a`` ("Remove template Item model") carried two Alembic-autogenerated
operations that were never hand-removed. Beyond dropping the template's ``item``
table — its actual purpose — it also dropped two database invariants created by
earlier migrations:

* ``uq_cashregistersession_single_open`` (created by ``f2a9c4e8b1d7``): at most one
  ``CashRegisterSession`` may be OPEN at a time. The partial unique index is what the
  ``except IntegrityError`` branch in ``crud.open_cash_session`` relies on; without it
  that branch is dead code and two concurrent opens both succeed.
* ``ck_product_stock_maximo_gte_minimo`` (created by ``bb4805f80102``): the min-max
  fill-to level cannot be below the reorder trigger. The product routes enforce it
  (``_ensure_stock_maximo``), but imports and direct writes bypass them.

Both objects are now declared in SQLModel metadata, so autogenerate can see them and
``alembic check`` can no longer lose them silently.

The upgrade tolerates environments where either object survived (a plain
``CREATE INDEX`` would fail there) and never mutates business data on its own: when
existing rows make the object impossible to create, it refuses to run and reports
them instead. Closing extra cash sessions or rewriting a product's stock levels is a
business decision, not a migration decision.

Revision ID: 39c9148ae5e4
Revises: 7af6fcde0f91
Create Date: 2026-09-10 17:11:27.395217

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39c9148ae5e4"
down_revision: str | None = "7af6fcde0f91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SINGLE_OPEN_INDEX = "uq_cashregistersession_single_open"
STOCK_MAXIMO_CHECK = "ck_product_stock_maximo_gte_minimo"


def _index_exists() -> bool:
    return (
        op.get_bind()
        .execute(
            sa.text(
                "select 1 from pg_indexes where schemaname = current_schema()"
                " and indexname = :name"
            ),
            {"name": SINGLE_OPEN_INDEX},
        )
        .first()
        is not None
    )


def _check_constraint_exists() -> bool:
    return (
        op.get_bind()
        .execute(
            sa.text(
                "select 1 from pg_constraint where conname = :name"
                " and conrelid = 'product'::regclass"
            ),
            {"name": STOCK_MAXIMO_CHECK},
        )
        .first()
        is not None
    )


def upgrade() -> None:
    connection = op.get_bind()

    if not _index_exists():
        open_sessions = connection.execute(
            sa.text(
                "select id::text, opened_at::text from cashregistersession"
                " where status = 'OPEN' order by opened_at"
            )
        ).all()
        if len(open_sessions) > 1:
            listing = "; ".join(f"{sid} (opened at {ts})" for sid, ts in open_sessions)
            raise RuntimeError(
                f"Refusing to restore {SINGLE_OPEN_INDEX}: "
                f"{len(open_sessions)} cash sessions are OPEN — {listing}. "
                "Leave at most one open (close the others through the app, or with an "
                "explicit UPDATE you have decided on) and re-run the migration. This "
                "migration never closes sessions on its own."
            )
        op.execute(
            f"CREATE UNIQUE INDEX {SINGLE_OPEN_INDEX}"
            " ON cashregistersession (status)"
            " WHERE status = 'OPEN'::cashsessionstatus"
        )

    if not _check_constraint_exists():
        violating = connection.execute(
            sa.text(
                "select id::text, stock_minimo::text, stock_maximo::text from product"
                " where stock_minimo is not null and stock_maximo < stock_minimo"
            )
        ).all()
        if violating:
            listing = "; ".join(f"{pid} (min {lo}, max {hi})" for pid, lo, hi in violating)
            raise RuntimeError(
                f"Refusing to add {STOCK_MAXIMO_CHECK}: {len(violating)} products have "
                f"stock_maximo below stock_minimo — {listing}. Fix those products and "
                "re-run the migration. This migration never rewrites business data on "
                "its own."
            )
        op.create_check_constraint(
            STOCK_MAXIMO_CHECK,
            "product",
            "stock_minimo IS NULL OR stock_maximo >= stock_minimo",
        )


def downgrade() -> None:
    # ``IF EXISTS`` on both: these objects predate this migration in some
    # environments — restoring them is the whole point — so a plain drop would
    # abort there instead of leaving the pre-migration shape.
    op.execute(f"DROP INDEX IF EXISTS {SINGLE_OPEN_INDEX}")
    op.execute(f"ALTER TABLE product DROP CONSTRAINT IF EXISTS {STOCK_MAXIMO_CHECK}")
