"""Add backup tables

Revision ID: 78485ea2f66a
Revises: 0163d9c9a091
Create Date: 2026-08-08 18:12:14.077781

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '78485ea2f66a'
down_revision = '0163d9c9a091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backupschedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='backupfrequency'), nullable=False),
    sa.Column('run_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('retention', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.Enum('SUCCESS', 'FAILED', name='backupstatus'), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restorestatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('IDLE', 'RUNNING', 'SUCCESS', 'FAILED', name='restorestate'), nullable=False),
    sa.Column('source_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('MANUAL', 'SCHEDULED', name='backupkind'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='backupstatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_filename'), 'backup', ['filename'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_filename'), table_name='backup')
    op.drop_table('backup')
    op.drop_table('restorestatus')
    op.drop_table('backupschedule')
    # PostgreSQL enum types persist across migrations; drop them explicitly so
    # a downgrade + re-upgrade does not fail with "type already exists".
    sa.Enum(name='backupfrequency').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='backupstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='backupkind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='restorestate').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
