"""Add saldo_inicial to DocumentPaymentAllocation

Revision ID: 790f83bd8af0
Revises: e272cd822e50
Create Date: 2026-08-23 11:49:59.369639

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '790f83bd8af0'
down_revision = 'e272cd822e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentpaymentallocation', sa.Column('saldo_inicial', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentpaymentallocation', 'saldo_inicial')
    # ### end Alembic commands ###
