"""Add report print margin setting

Revision ID: 7af6fcde0f91
Revises: c9719855c36c
Create Date: 2026-09-09 17:44:29.846331

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7af6fcde0f91'
down_revision = 'c9719855c36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'businesssettings',
        sa.Column(
            'print_margin_report_mm',
            sa.Integer(),
            nullable=False,
            server_default='10',
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesssettings', 'print_margin_report_mm')
    # ### end Alembic commands ###
