"""Add document and finance core models

Revision ID: 9bcc16058b2b
Revises: f962c8ec15e6
Create Date: 2026-07-28 17:56:15.457908

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9bcc16058b2b'
down_revision = 'f962c8ec15e6'
branch_labels = None
depends_on = None


# Enum types are created once up-front (checkfirst) and referenced with
# create_type=False so that types used by several tables are not re-created.
DOCUMENT_OPERATION = postgresql.ENUM(
    'VENTA', 'COMPRA', 'COTIZACION', 'AJUSTE',
    name='documentoperation',
    create_type=False,
)
COUNTERPART_TYPE = postgresql.ENUM(
    'CUSTOMER', 'SUPPLIER', name='counterparttype', create_type=False
)
FINANCIAL_ACCOUNT_TYPE = postgresql.ENUM(
    'EFECTIVO', 'BANCO', 'TARJETA', 'DIGITAL', 'CUENTA_CLIENTE', 'CUENTA_PROVEEDOR',
    name='financialaccounttype',
    create_type=False,
)
DOCUMENT_STATUS = postgresql.ENUM(
    'ACTIVE', 'VOIDED', name='documentstatus', create_type=False
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    for enum_type in (
        'documentoperation',
        'counterparttype',
        'financialaccounttype',
        'documentstatus',
    ):
        values = {
            'documentoperation': ('VENTA', 'COMPRA', 'COTIZACION', 'AJUSTE'),
            'counterparttype': ('CUSTOMER', 'SUPPLIER'),
            'financialaccounttype': (
                'EFECTIVO', 'BANCO', 'TARJETA', 'DIGITAL',
                'CUENTA_CLIENTE', 'CUENTA_PROVEEDOR',
            ),
            'documentstatus': ('ACTIVE', 'VOIDED'),
        }[enum_type]
        postgresql.ENUM(*values, name=enum_type).create(bind, checkfirst=True)
    op.create_table('documenttype',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('operation', DOCUMENT_OPERATION, nullable=False),
    sa.Column('signo_stock', sa.Integer(), nullable=False),
    sa.Column('signo_caja', sa.Integer(), nullable=False),
    sa.Column('es_fiscal', sa.Boolean(), nullable=False),
    sa.Column('tipo_contraparte', COUNTERPART_TYPE, nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documenttype_prefix'), 'documenttype', ['prefix'], unique=True)
    op.create_table('financialaccount',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tipo', FINANCIAL_ACCOUNT_TYPE, nullable=False),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_type_id', sa.Uuid(), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contraparte_type', COUNTERPART_TYPE, nullable=True),
    sa.Column('contraparte_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('estado', DOCUMENT_STATUS, nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('parent_document_id', sa.Uuid(), nullable=True),
    sa.Column('cae', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('cae_vto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['documenttype.id'], ),
    sa.ForeignKeyConstraint(['parent_document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_contraparte_id'), 'document', ['contraparte_id'], unique=False)
    op.create_index(op.f('ix_document_numero'), 'document', ['numero'], unique=True)
    op.create_table('documentsequence',
    sa.Column('document_type_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['documenttype.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_type_id', 'year')
    )
    op.create_table('paymentmethod',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('financial_account_id', sa.Uuid(), nullable=False),
    sa.Column('requiere_conciliacion', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financialaccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentpayment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comision_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fecha_acreditacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['paymentmethod.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documenttax',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('tax_id', sa.Uuid(), nullable=False),
    sa.Column('base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_id'], ['tax.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('precio_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('descuento_monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_line', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['productvariant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentlinetax',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_line_id', sa.Uuid(), nullable=False),
    sa.Column('tax_id', sa.Uuid(), nullable=False),
    sa.Column('base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('aplicado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_line_id'], ['documentline.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_id'], ['tax.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentlinetax')
    op.drop_table('documentline')
    op.drop_table('documenttax')
    op.drop_table('documentpayment')
    op.drop_table('paymentmethod')
    op.drop_table('documentsequence')
    op.drop_index(op.f('ix_document_numero'), table_name='document')
    op.drop_index(op.f('ix_document_contraparte_id'), table_name='document')
    op.drop_table('document')
    op.drop_table('financialaccount')
    op.drop_index(op.f('ix_documenttype_prefix'), table_name='documenttype')
    op.drop_table('documenttype')
    # ### end Alembic commands ###
