"""Add business settings configuration fields

Revision ID: b4e0259e8d9b
Revises: e8fa682a7a8b
Create Date: 2026-08-16 18:54:01.951617

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b4e0259e8d9b'
down_revision = 'e8fa682a7a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    numberformat = sa.Enum('ES', 'EN', name='numberformat')
    stockpolicy = sa.Enum('BLOCK', 'WARN', name='stockpolicy')
    localepreference = sa.Enum('ES', 'EN', name='localepreference')
    numberformat.create(op.get_bind(), checkfirst=True)
    stockpolicy.create(op.get_bind(), checkfirst=True)
    localepreference.create(op.get_bind(), checkfirst=True)
    op.add_column('businesssettings', sa.Column('payment_method_default_id', sa.Uuid(), nullable=True))
    op.add_column('businesssettings', sa.Column('number_format', numberformat, nullable=False, server_default='EN'))
    op.add_column('businesssettings', sa.Column('logo_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('businesssettings', sa.Column('stock_policy', stockpolicy, nullable=False, server_default='WARN'))
    op.add_column('businesssettings', sa.Column('default_locale', localepreference, nullable=False, server_default='EN'))
    op.create_foreign_key('fk_businesssettings_payment_method_default_id', 'businesssettings', 'paymentmethod', ['payment_method_default_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_businesssettings_payment_method_default_id', 'businesssettings', type_='foreignkey')
    op.drop_column('businesssettings', 'default_locale')
    op.drop_column('businesssettings', 'stock_policy')
    op.drop_column('businesssettings', 'logo_path')
    op.drop_column('businesssettings', 'number_format')
    op.drop_column('businesssettings', 'payment_method_default_id')
    # PostgreSQL enum types persist across migrations; drop them explicitly so
    # a downgrade + re-upgrade does not fail with "type already exists".
    sa.Enum(name='numberformat').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='stockpolicy').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='localepreference').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
