"""Add SupplierProduct model

Revision ID: c024b6603c1f
Revises: c3bf3c241bcf
Create Date: 2026-08-04 16:28:12.267606

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c024b6603c1f'
down_revision = 'c3bf3c241bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplierproduct',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('costo_anterior', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('es_referencia', sa.Boolean(), nullable=False),
    sa.Column('es_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('supplier_id', 'product_id')
    )
    op.create_index(op.f('ix_supplierproduct_product_id'), 'supplierproduct', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplierproduct_supplier_id'), 'supplierproduct', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplierproduct_supplier_id'), table_name='supplierproduct')
    op.drop_index(op.f('ix_supplierproduct_product_id'), table_name='supplierproduct')
    op.drop_table('supplierproduct')
    # ### end Alembic commands ###
