"""Add stock and finance ledger models

Revision ID: c3bf3c241bcf
Revises: f75f6f78e9dc
Create Date: 2026-08-04 08:31:23.736184

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c3bf3c241bcf'
down_revision = 'f75f6f78e9dc'
branch_labels = None
depends_on = None


# Enum types are created once up-front (checkfirst) and referenced with
# create_type=False so that types used by several tables are not re-created.
ACCOUNT_MOVEMENT_TYPE = postgresql.ENUM(
    'PAGO', 'COBRO', 'COMISION', 'TRANSFERENCIA', 'AJUSTE',
    name='accountmovementtype',
    create_type=False,
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM(
        'PAGO', 'COBRO', 'COMISION', 'TRANSFERENCIA', 'AJUSTE',
        name='accountmovementtype',
    ).create(op.get_bind(), checkfirst=True)
    op.create_table('transfer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_account_id', sa.Uuid(), nullable=False),
    sa.Column('to_account_id', sa.Uuid(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_account_id'], ['financialaccount.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['financialaccount.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accountmovement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('financial_account_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('payment_method_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_id', sa.Uuid(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo', ACCOUNT_MOVEMENT_TYPE, nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_acreditacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financialaccount.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['paymentmethod.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accountmovement_financial_account_id'), 'accountmovement', ['financial_account_id'], unique=False)
    op.create_table('customeraccountmovement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customeraccountmovement_customer_id'), 'customeraccountmovement', ['customer_id'], unique=False)
    op.create_table('supplieraccountmovement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplieraccountmovement_supplier_id'), 'supplieraccountmovement', ['supplier_id'], unique=False)
    op.create_table('stockmovement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_line_id', sa.Uuid(), nullable=True),
    sa.Column('signo', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['document_line_id'], ['documentline.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['productvariant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockmovement_product_id'), 'stockmovement', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stockmovement_product_id'), table_name='stockmovement')
    op.drop_table('stockmovement')
    op.drop_index(op.f('ix_supplieraccountmovement_supplier_id'), table_name='supplieraccountmovement')
    op.drop_table('supplieraccountmovement')
    op.drop_index(op.f('ix_customeraccountmovement_customer_id'), table_name='customeraccountmovement')
    op.drop_table('customeraccountmovement')
    op.drop_index(op.f('ix_accountmovement_financial_account_id'), table_name='accountmovement')
    op.drop_table('accountmovement')
    op.drop_table('transfer')
    postgresql.ENUM(
        'PAGO', 'COBRO', 'COMISION', 'TRANSFERENCIA', 'AJUSTE',
        name='accountmovementtype',
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
