"""Remove template Item model

Revision ID: d61ddf38636a
Revises: 05cf4ac88022
Create Date: 2026-09-08 19:05:30.347933

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d61ddf38636a"
down_revision = "05cf4ac88022"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item")
    op.drop_index(
        op.f("uq_cashregistersession_single_open"),
        table_name="cashregistersession",
        postgresql_where="(status = 'OPEN'::cashsessionstatus)",
    )
    op.drop_constraint(
        op.f("ck_product_stock_maximo_gte_minimo"), "product", type_="check"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_product_stock_maximo_gte_minimo"),
        "product",
        "stock_minimo IS NULL OR stock_maximo >= stock_minimo",
    )
    op.create_index(
        op.f("uq_cashregistersession_single_open"),
        "cashregistersession",
        ["status"],
        unique=True,
        postgresql_where="(status = 'OPEN'::cashsessionstatus)",
    )
    op.create_table(
        "item",
        sa.Column(
            "description", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            name=op.f("item_owner_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("item_pkey")),
    )
    # ### end Alembic commands ###
