"""Add CashRegisterSession model

Revision ID: e272cd822e50
Revises: b4e0259e8d9b
Create Date: 2026-08-19 00:26:32.545031

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e272cd822e50'
down_revision = 'b4e0259e8d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashregistersession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('closed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('cash_account_id', sa.Uuid(), nullable=False),
    sa.Column('opening_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opening_source_account_id', sa.Uuid(), nullable=False),
    sa.Column('counted_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='cashsessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cash_account_id'], ['financialaccount.id'], ),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['opening_source_account_id'], ['financialaccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accountmovement', sa.Column('cash_session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_accountmovement_cash_session_id'), 'accountmovement', ['cash_session_id'], unique=False)
    op.create_foreign_key('fk_accountmovement_cash_session', 'accountmovement', 'cashregistersession', ['cash_session_id'], ['id'])
    op.add_column('document', sa.Column('cash_session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_document_cash_session_id'), 'document', ['cash_session_id'], unique=False)
    op.create_foreign_key('fk_document_cash_session', 'document', 'cashregistersession', ['cash_session_id'], ['id'])
    op.add_column('paymentmethod', sa.Column('is_cash_drawer', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('transfer', sa.Column('cash_session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_transfer_cash_session_id'), 'transfer', ['cash_session_id'], unique=False)
    op.create_foreign_key('fk_transfer_cash_session', 'transfer', 'cashregistersession', ['cash_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transfer_cash_session', 'transfer', type_='foreignkey')
    op.drop_index(op.f('ix_transfer_cash_session_id'), table_name='transfer')
    op.drop_column('transfer', 'cash_session_id')
    op.drop_column('paymentmethod', 'is_cash_drawer')
    op.drop_constraint('fk_document_cash_session', 'document', type_='foreignkey')
    op.drop_index(op.f('ix_document_cash_session_id'), table_name='document')
    op.drop_column('document', 'cash_session_id')
    op.drop_constraint('fk_accountmovement_cash_session', 'accountmovement', type_='foreignkey')
    op.drop_index(op.f('ix_accountmovement_cash_session_id'), table_name='accountmovement')
    op.drop_column('accountmovement', 'cash_session_id')
    op.drop_table('cashregistersession')
    # ### end Alembic commands ###
