"""Add timezone to business settings

Revision ID: e8fa682a7a8b
Revises: f96e2178c3b2
Create Date: 2026-08-16 16:50:18.799228

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e8fa682a7a8b'
down_revision = 'f96e2178c3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'businesssettings',
        sa.Column(
            'timezone',
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
            server_default='America/Argentina/Buenos_Aires',
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesssettings', 'timezone')
    # ### end Alembic commands ###
