"""Add void mirror type and parent line link

Revision ID: f75f6f78e9dc
Revises: 9bcc16058b2b
Create Date: 2026-07-28 18:21:18.876757

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f75f6f78e9dc'
down_revision = '9bcc16058b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentline', sa.Column('parent_line_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_documentline_parent_line_id',
        'documentline', 'documentline',
        ['parent_line_id'], ['id'],
    )
    op.add_column('documenttype', sa.Column('void_document_type_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_documenttype_void_document_type_id',
        'documenttype', 'documenttype',
        ['void_document_type_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documenttype_void_document_type_id', 'documenttype', type_='foreignkey')
    op.drop_column('documenttype', 'void_document_type_id')
    op.drop_constraint('fk_documentline_parent_line_id', 'documentline', type_='foreignkey')
    op.drop_column('documentline', 'parent_line_id')
    # ### end Alembic commands ###
