"""Add Customer and Supplier models

Revision ID: f962c8ec15e6
Revises: 27c625ca40f7
Create Date: 2026-07-28 17:29:22.098150

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f962c8ec15e6'
down_revision = '27c625ca40f7'
branch_labels = None
depends_on = None


# The 'taxcondition' enum type already exists (created by the BusinessSettings
# migration); reference it without re-creating it.
TAXCONDITION = postgresql.ENUM(
    'RI', 'MONOTRIBUTO', 'EXENTO', 'CONSUMIDOR_FINAL',
    name='taxcondition',
    create_type=False,
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('razon_social', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('condicion_fiscal', TAXCONDITION, nullable=False),
    sa.Column('limite_credito', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_documento'), 'customer', ['documento'], unique=True)
    op.create_table('supplier',
    sa.Column('razon_social', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('condicion_fiscal', TAXCONDITION, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_documento'), 'supplier', ['documento'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_documento'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_customer_documento'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
