/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSuppliersRouteImport } from './routes/_layout/suppliers'
import { Route as LayoutStockRouteImport } from './routes/_layout/stock'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSellRouteImport } from './routes/_layout/sell'
import { Route as LayoutReportsRouteImport } from './routes/_layout/reports'
import { Route as LayoutPaymentsRouteImport } from './routes/_layout/payments'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutDocumentsRouteImport } from './routes/_layout/documents'
import { Route as LayoutCustomersRouteImport } from './routes/_layout/customers'
import { Route as LayoutBuyRouteImport } from './routes/_layout/buy'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCatalogProductsRouteImport } from './routes/_layout/catalog/products'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSuppliersRoute = LayoutSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStockRoute = LayoutStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSellRoute = LayoutSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportsRoute = LayoutReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPaymentsRoute = LayoutPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentsRoute = LayoutDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCustomersRoute = LayoutCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuyRoute = LayoutBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCatalogProductsRoute = LayoutCatalogProductsRouteImport.update({
  id: '/catalog/products',
  path: '/catalog/products',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/buy': typeof LayoutBuyRoute
  '/customers': typeof LayoutCustomersRoute
  '/documents': typeof LayoutDocumentsRoute
  '/items': typeof LayoutItemsRoute
  '/payments': typeof LayoutPaymentsRoute
  '/reports': typeof LayoutReportsRoute
  '/sell': typeof LayoutSellRoute
  '/settings': typeof LayoutSettingsRoute
  '/stock': typeof LayoutStockRoute
  '/suppliers': typeof LayoutSuppliersRoute
  '/catalog/products': typeof LayoutCatalogProductsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/buy': typeof LayoutBuyRoute
  '/customers': typeof LayoutCustomersRoute
  '/documents': typeof LayoutDocumentsRoute
  '/items': typeof LayoutItemsRoute
  '/payments': typeof LayoutPaymentsRoute
  '/reports': typeof LayoutReportsRoute
  '/sell': typeof LayoutSellRoute
  '/settings': typeof LayoutSettingsRoute
  '/stock': typeof LayoutStockRoute
  '/suppliers': typeof LayoutSuppliersRoute
  '/': typeof LayoutIndexRoute
  '/catalog/products': typeof LayoutCatalogProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/buy': typeof LayoutBuyRoute
  '/_layout/customers': typeof LayoutCustomersRoute
  '/_layout/documents': typeof LayoutDocumentsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/payments': typeof LayoutPaymentsRoute
  '/_layout/reports': typeof LayoutReportsRoute
  '/_layout/sell': typeof LayoutSellRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/stock': typeof LayoutStockRoute
  '/_layout/suppliers': typeof LayoutSuppliersRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/catalog/products': typeof LayoutCatalogProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/buy'
    | '/customers'
    | '/documents'
    | '/items'
    | '/payments'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/stock'
    | '/suppliers'
    | '/catalog/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/buy'
    | '/customers'
    | '/documents'
    | '/items'
    | '/payments'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/stock'
    | '/suppliers'
    | '/'
    | '/catalog/products'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/buy'
    | '/_layout/customers'
    | '/_layout/documents'
    | '/_layout/items'
    | '/_layout/payments'
    | '/_layout/reports'
    | '/_layout/sell'
    | '/_layout/settings'
    | '/_layout/stock'
    | '/_layout/suppliers'
    | '/_layout/'
    | '/_layout/catalog/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/suppliers': {
      id: '/_layout/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof LayoutSuppliersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stock': {
      id: '/_layout/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof LayoutStockRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sell': {
      id: '/_layout/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof LayoutSellRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reports': {
      id: '/_layout/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof LayoutReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/payments': {
      id: '/_layout/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof LayoutPaymentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documents': {
      id: '/_layout/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof LayoutDocumentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/customers': {
      id: '/_layout/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof LayoutCustomersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/buy': {
      id: '/_layout/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof LayoutBuyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog/products': {
      id: '/_layout/catalog/products'
      path: '/catalog/products'
      fullPath: '/catalog/products'
      preLoaderRoute: typeof LayoutCatalogProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBuyRoute: typeof LayoutBuyRoute
  LayoutCustomersRoute: typeof LayoutCustomersRoute
  LayoutDocumentsRoute: typeof LayoutDocumentsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPaymentsRoute: typeof LayoutPaymentsRoute
  LayoutReportsRoute: typeof LayoutReportsRoute
  LayoutSellRoute: typeof LayoutSellRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStockRoute: typeof LayoutStockRoute
  LayoutSuppliersRoute: typeof LayoutSuppliersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCatalogProductsRoute: typeof LayoutCatalogProductsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBuyRoute: LayoutBuyRoute,
  LayoutCustomersRoute: LayoutCustomersRoute,
  LayoutDocumentsRoute: LayoutDocumentsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPaymentsRoute: LayoutPaymentsRoute,
  LayoutReportsRoute: LayoutReportsRoute,
  LayoutSellRoute: LayoutSellRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStockRoute: LayoutStockRoute,
  LayoutSuppliersRoute: LayoutSuppliersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCatalogProductsRoute: LayoutCatalogProductsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
